<a href="https://colab.research.google.com/github/24tq1a6677-kola/youtube-sentiment-dashboard/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
a=([20,30,40])
var=pd.Series(a,index=["x","y","z"])
print(var)

x    20
y    30
z    40
dtype: int64

In [ ]:
import pandas as pd
car={
    "type":"deisel",
    "color":"black",
    "model":"BMW"
}
var=pd.Series(car)
print(var)

type     deisel
color     black
model       BMW
dtype: object

In [ ]:
df = pd.read_csv('customers-100.csv')

In [ ]:
df.size

1200

In [ ]:
print('Summary statistics for numerical columns:')
display(df.describe())

Summary statistics for numerical columns:

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [ ]:
print('\nDataFrame information (data types, non-null values):')
df.info()

DataFrame information (data types, non-null values):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [ ]:
print('\n,the size of this file is ')
display(df.size)

,the size of this file is

1200

In [ ]:
df.shape

(100, 12)

In [ ]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
df.axes

[RangeIndex(start=0, stop=100, step=1),
 Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
        'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
        'Website'],
       dtype='object')]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [ ]:
df=df.set_index('First Name')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

### Original DataFrame (`df`): Notice the 'First Name' is a regular column and the index is a default numerical range.

In [ ]:
display(df.head())

### Indexed DataFrame (`df_indexed`): Now 'First Name' is the index, and it's no longer present as a regular column.

In [ ]:
display(df.head())

,Index,Customer Id,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
First Name,,,,,,,,,,,
Sheryl,1,DD37Cf93aecA6Dc,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
Preston,2,1Ef7b82A4CAAD10,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
Roy,3,6F94879bDAfE5a6,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
Linda,4,5Cef8BFA16c5e3c,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
Joanna,5,053d585Ab6b3159,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [ ]:
import pandas as pd
df.head()

,Index,Customer Id,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
First Name,,,,,,,,,,,
Sheryl,1,DD37Cf93aecA6Dc,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
Preston,2,1Ef7b82A4CAAD10,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
Roy,3,6F94879bDAfE5a6,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
Linda,4,5Cef8BFA16c5e3c,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
Joanna,5,053d585Ab6b3159,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [ ]:
df[df['City']=='East Leonard']

,Index,Customer Id,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
First Name,,,,,,,,,,,
Sheryl,1,DD37Cf93aecA6Dc,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/

In [ ]:
df.tail(10)

,Index,Customer Id,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
First Name,,,,,,,,,,,
Nina,91,5ef6d3eefdD43bE,Chavez,Byrd-Campbell,Cassidychester,Bhutan,053-344-3205,+1-330-920-5422x571,elliserica@frank.com,2020-03-26,https://www.pugh.com/
Shane,92,98b3aeDcC3B9FF3,Foley,Rocha-Hart,South Dannymouth,Hungary,+1-822-569-0302,001-626-114-5844x55073,nsteele@sparks.com,2021-07-06,https://www.holt-sparks.com/
Collin,93,aAb6AFc7AfD0fF3,Ayers,Lamb-Peterson,South Lonnie,Anguilla,404-645-5351x012,001-257-582-8850x8516,dudleyemily@gonzales.biz,2021-06-29,http://www.ruiz.com/
Sherry,94,54B5B5Fe9F1B6C5,Young,"Lee, Lucero and Johnson",Frankchester,Solomon Islands,158-687-1764,(438)375-6207x003,alan79@gates-mclaughlin.com,2021-04-04,https://travis.net/
Darrell,95,BE91A0bdcA49Bbc,Douglas,"Newton, Petersen and Mathis",Daisyborough,Mali,001-084-845-9524x1777,001-769-564-6303,grayjean@lowery-good.com,2022-02-17,https://banks.biz/
Karl,96,cb8E23e48d22Eae,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
Lynn,97,CeD220bdAaCfaDf,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
Fred,98,28CDbC0dFe4b1Db,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
Yvonne,99,c23d1D9EE8DEB0A,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
Clarence,100,2354a0E336A91A1,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
df[df['Country']=='Solomon Islands']

,Index,Customer Id,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
First Name,,,,,,,,,,,
Jordan,38,7a1Ee69F4fF4B4D,Gay,Glover and Sons,South Walter,Solomon Islands,7208417020,8035336772,tiffanydavies@harris-mcfarland.org,2021-02-24,http://www.lee.org/
Regina,75,D01Af0AF7cBbFeA,Stein,Guzman-Brown,Raystad,Solomon Islands,001-469-848-0724x4407,001-085-360-4426x00357,zrosario@rojas-hardin.net,2022-01-15,http://www.johnston.info/
Sherry,94,54B5B5Fe9F1B6C5,Young,"Lee, Lucero and Johnson",Frankchester,Solomon Islands,158-687-1764,(438)375-6207x003,alan79@gates-mclaughlin.com,2021-04-04,https://travis.net/
Fred,98,28CDbC0dFe4b1Db,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/

In [ ]:
f=df[df['Country']=='Solomon Islands']
f.reset_index(inplace=True)
f

,First Name,Index,Customer Id,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,Jordan,38,7a1Ee69F4fF4B4D,Gay,Glover and Sons,South Walter,Solomon Islands,7208417020,8035336772,tiffanydavies@harris-mcfarland.org,2021-02-24,http://www.lee.org/
1,Regina,75,D01Af0AF7cBbFeA,Stein,Guzman-Brown,Raystad,Solomon Islands,001-469-848-0724x4407,001-085-360-4426x00357,zrosario@rojas-hardin.net,2022-01-15,http://www.johnston.info/
2,Sherry,94,54B5B5Fe9F1B6C5,Young,"Lee, Lucero and Johnson",Frankchester,Solomon Islands,158-687-1764,(438)375-6207x003,alan79@gates-mclaughlin.com,2021-04-04,https://travis.net/
3,Fred,98,28CDbC0dFe4b1Db,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/

In [ ]:
import pandas as pd
df=pd.read_csv("unclean_data.csv", encoding='latin1')

In [ ]:
df.shape

(14, 16)

In [ ]:
df.sample(7)

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
7,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,NaN
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
10,Batman v Superman: Dawn of Justice?ÿ,673,183.0,NaN,2000,15000,330249062,NaN,24450.0,NaN,3018,250000000,2016,NaN,6.9,2016.0
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
9,Harry Potter and the Half-Blood Prince?ÿ,375,153.0,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,NaN

In [ ]:
df.columns=df.columns.str.strip().str.title().str.replace("_"," ")

In [ ]:
print(df.columns)

Index(['Movie Title', 'Num Critic For Reviews', 'Duration',
       'Director Facebook Likes', 'Actor 3 Facebook Likes',
       'Actor 1 Facebook Likes', 'Gross', 'Num Voted Users',
       'Cast Total Facebook Likes', 'Facenumber In Poster',
       'Num User For Reviews', 'Budget', 'Title Year',
       'Actor 2 Facebook Likes', 'Imdb Score', 'Title Year.1'],
      dtype='object')

In [ ]:
print("before:",len(df))
df=df.drop_duplicates()
print("after:",len(df))

before: 14
after: 14

In [ ]:
df

,Movie Title,Num Critic For Reviews,Duration,Director Facebook Likes,Actor 3 Facebook Likes,Actor 1 Facebook Likes,Gross,Num Voted Users,Cast Total Facebook Likes,Facenumber In Poster,Num User For Reviews,Budget,Title Year,Actor 2 Facebook Likes,Imdb Score,Title Year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN
5,Spider-Man 3?ÿ,392,156.0,23,4000,24000,336530303,383056.0,46055.0,NaN,1902,258000000,2007,11000.0,6.2,2007.0
6,Tangled?ÿ,324,NaN,15,284,799,200807262,294810.0,NaN,1.0,387,260000000,2010,553.0,7.8,NaN
7,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,NaN
8,Avengers: Age of Ultron?ÿ,635,141.0,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
9,Harry Potter and the Half-Blood Prince?ÿ,375,153.0,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,NaN
10,Batman v Superman: Dawn of Justice?ÿ,673,183.0,NaN,2000,15000,330249062,NaN,24450.0,NaN,3018,250000000,2016,NaN,6.9,2016.0
11,Superman Returns?ÿ,434,169.0,NaN,903,18000,200069408,240396.0,NaN,2.0,2367,209000000,2006,10000.0,6.1,NaN
12,Quantum of Solace?ÿ,403,106.0,395,393,451,168368427,330784.0,2023.0,1.0,1243,200000000,2008,412.0,6.7,2008.0
13,Pirates of the Caribbean: Dead Man's Chest?ÿ,313,151.0,563,1000,40000,423032628,522040.0,48486.0,2.0,1832,225000000,2006,5000.0,7.3,2008.0

In [ ]:
df.isnull().sum()

Movie Title                  0
Num Critic For Reviews       0
Duration                     3
Director Facebook Likes      2
Actor 3 Facebook Likes       0
Actor 1 Facebook Likes       0
Gross                        0
Num Voted Users              1
Cast Total Facebook Likes    2
Facenumber In Poster         5
Num User For Reviews         0
Budget                       0
Title Year                   0
Actor 2 Facebook Likes       1
Imdb Score                   0
Title Year.1                 7
dtype: int64

In [ ]:
df.fillna(df['Facenumber In Poster'].mean(),inplace=True)
df

,Movie Title,Num Critic For Reviews,Duration,Director Facebook Likes,Actor 3 Facebook Likes,Actor 1 Facebook Likes,Gross,Num Voted Users,Cast Total Facebook Likes,Facenumber In Poster,Num User For Reviews,Budget,Title Year,Actor 2 Facebook Likes,Imdb Score,Title Year.1
0,Avatar?ÿ,723,178.000000,10,855,1000,760505847,8.862040e+05,4834.000000,2.111111,3054,237000000,2009,936.000000,7.9,2009.000000
1,Pirates of the Caribbean: At World's End?ÿ,302,2.111111,563,1000,40000,309404152,4.712200e+05,48350.000000,2.111111,1238,300000000,2007,5000.000000,7.1,2.111111
2,Spectre?ÿ,602,148.000000,20,161,11000,200074175,2.758680e+05,11700.000000,1.000000,994,245000000,2015,393.000000,6.8,2015.000000
3,The Dark Knight Rises?ÿ,813,2.111111,22000,23000,27000,448130642,1.144337e+06,106759.000000,2.111111,2701,250000000,2012,23000.000000,8.5,2.111111
4,John Carter?ÿ,462,132.000000,"""475""",530,640,73058679,2.122040e+05,1873.000000,1.000000,738,263700000,2012,632.000000,6.6,2.111111
5,Spider-Man 3?ÿ,392,156.000000,23,4000,24000,336530303,3.830560e+05,46055.000000,2.111111,1902,258000000,2007,11000.000000,6.2,2007.000000
6,Tangled?ÿ,324,2.111111,15,284,799,200807262,2.948100e+05,2.111111,1.000000,387,260000000,2010,553.000000,7.8,2.111111
7,Avengers: Age of Ultron?ÿ,635,141.000000,10,19000,26000,458991599,4.626690e+05,92000.000000,4.000000,1117,250000000,2015,21000.000000,7.5,2.111111
8,Avengers: Age of Ultron?ÿ,635,141.000000,10,19000,26000,458991599,4.626690e+05,92000.000000,4.000000,1117,250000000,2015,21000.000000,7.5,2015.000000
9,Harry Potter and the Half-Blood Prince?ÿ,375,153.000000,282,10000,25000,301956980,3.217950e+05,58753.000000,3.000000,973,250000000,2009,11000.000000,7.5,2.111111
10,Batman v Superman: Dawn of Justice?ÿ,673,183.000000,2.111111,2000,15000,330249062,2.111111e+00,24450.000000,2.111111,3018,250000000,2016,2.111111,6.9,2016.000000
11,Superman Returns?ÿ,434,169.000000,2.111111,903,18000,200069408,2.403960e+05,2.111111,2.000000,2367,209000000,2006,10000.000000,6.1,2.111111
12,Quantum of Solace?ÿ,403,106.000000,395,393,451,168368427,3.307840e+05,2023.000000,1.000000,1243,200000000,2008,412.000000,6.7,2008.000000
13,Pirates of the Caribbean: Dead Man's Chest?ÿ,313,151.000000,563,1000,40000,423032628,5.220400e+05,48486.000000,2.000000,1832,225000000,2006,5000.000000,7.3,2008.000000

In [ ]:
df.isnull().sum()

Movie Title                  0
Num Critic For Reviews       0
Duration                     0
Director Facebook Likes      0
Actor 3 Facebook Likes       0
Actor 1 Facebook Likes       0
Gross                        0
Num Voted Users              0
Cast Total Facebook Likes    0
Facenumber In Poster         0
Num User For Reviews         0
Budget                       0
Title Year                   0
Actor 2 Facebook Likes       0
Imdb Score                   0
Title Year.1                 0
dtype: int64